# Linter Options
options:
# Don't merge default rules
merge-default-rules: false
# Set the formatter to 'html'
#formatter: html
formatter: stylish
# Output file instead of logging results
#output-file: 'linters/sass-lint.html'

# Raise an error if more than 50 warnings are generated
#max-warnings: 50

# File Options
files:
  include: 'source/css/scss/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'

# Rule Configuration
rules:

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/attribute-quotes.md
  attribute-quotes: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/border-zero.md
  border-zero:
    - 0
    - convention: none

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/brace-style.md
  brace-style: 2
  # defaults to 1tbs

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/class-name-format.md
  class-name-format: 0
  # allow-leading-underscore: true/false (defaults to true)
  # convention: 'hyphenatedlowercase' (default), camelcase, snakecase, strictbem, hyphenatedbem, or a Regular Expression that the class name must match (e.g. ^[_A-Z]+$)
  # convention-explanation: Custom explanation to display to the user if a class doesn't adhere to the convention
  # ignore: Array of names to ignore

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/declarations-before-nesting.md
  declarations-before-nesting: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/empty-line-between-blocks.md
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/extends-before-declarations.md
  extends-before-declarations: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/extends-before-mixins.md
  extends-before-mixins: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/final-newline.md
  final-newline: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-attribute-nesting.md
  force-attribute-nesting: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-element-nesting.md
  force-element-nesting: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-pseudo-nesting.md
  force-pseudo-nesting: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/hex-length.md
  hex-length: 0
  # style: short/long

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/hex-notation.md
  hex-notation: 0
  #style: lowercase/uppercase

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/indentation.md
  indentation: 
    - 2
    - 
      size: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/leading-zero.md
  leading-zero:
    - 0
    - include: false

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/mixins-before-declarations.md
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/mixin-name-format.md
  mixin-name-format: 0
  # allow-leading-underscore: true/false (defaults to true)
  # convention: 'hyphenatedlowercase' (default), camelcase, snakecase, strictbem, hyphenatedbem, or a Regular Expression that the variable name must match (e.g. ^[_A-Z]+$)
  # convention-explanation: Custom explanation to display to the user if a mixin doesn't adhere to the convention

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/nesting-depth.md
  nesting-depth:
    - 2
    - max-depth: 4

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-color-keywords.md 
  no-color-keywords: 0

# We should not use multiline comments, rather do this: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-css-comments.md
  no-css-comments: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-color-literals.md
  no-color-literals: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-duplicate-properties.md
  no-duplicate-properties: 2

#ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-empty-rulesets.md
  no-empty-rulesets: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-ids.md
  no-ids: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-important.md
  no-important: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-mergeable-selectors.md
# This one can have a whitelist with an array of selectors
  no-mergeable-selectors: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-misspelled-properties.md 
  no-misspelled-properties:
    - 2
    # -
    #   'extra-properties':
    #   - 'transit1on'

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-qualifying-elements.md
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-trailing-whitespace.md
  no-trailing-whitespace: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-trailing-zero.md
  no-trailing-zero: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-transition-all.md
  no-transition-all: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-universal-selectors.md
  no-universal-selector: 0

# Disabling this for now. Should be turned on, and use autoprefixer to add vendor-prefixes.
  no-vendor-prefixes: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/one-declaration-per-line.md
  one-declaration-per-line: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/placeholder-in-extend.md
  placeholder-in-extend: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-sort-order.md
# order: 'alphabetical', 'concentric', 'recess', 'smacss', or [array of properties] (defaults to alphabetical. 
  property-sort-order:
    - 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-units.md
  property-units: 0
    # global: ['em', 'px', 'rem', etc] defaults to [] or all units allowed
    # per-property: { width: ['rem', 'px', etc], height: ['rem', 'px', etc], } defaults to {} or no property-specific units  

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/pseudo-element.md
  pseudo-element: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/quotes.md 
  quotes: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/single-line-per-selector.md
  single-line-per-selector: 2

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/shorthand-values.md
  shorthand-values: 0

#ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-bang.md
  space-after-bang: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-colon.md
  space-after-colon: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-comma.md
  space-after-comma: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-around-operator.md
  space-around-operator: 0
#    - include: true/false 

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-brace.md
  space-before-brace: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-bang.md
  space-before-bang: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-colon.md
  space-before-colon: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-between-parens.md
  space-between-parens: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/trailing-semicolon.md
  trailing-semicolon: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/url-quotes.md
  url-quotes: 0

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/variable-name-format.md
  variable-name-format: 0
  # allow-leading-underscore: true/false (defaults to true)
  # convention: 'hyphenatedlowercase' (default), camelcase, snakecase, strictbem, hyphenatedbem, or a Regular Expression that the variable name must match (e.g. ^[_A-Z]+$)
  # convention-explanation: Custom explanation to display to the user if a variable doesn't adhere to the convention

# ref: https://github.com/sasstools/sass-lint/blob/master/docs/rules/zero-unit.md
  zero-unit: 0





#  extends-before-mixins: 2
#  extends-before-declarations: 2
#  placeholder-in-extend: 2
#  mixins-before-declarations:
#    - 2
#    -
#      exclude:
#        - breakpoint
#        - mq

#  no-warn: 1
#  no-debug: 1
#  no-ids: 2
#  no-important: 2
#  hex-notation:
#    - 2
#    -
#      style: uppercase
#  indentation:
#    - 2
#    -
#      size: 2
#  property-sort-order:
#    - 1
#    -
#      order: alphabetical

#      ignore-custom-properties: true
#  variable-for-property:
#    - 2
#    -
#      properties:
#        - margin
#        - content